# version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
#      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - proxy-network

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - proxy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 5013:80
    networks:
      - proxy-network

## HAProxy Load Balancer
  ha-web2:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    volumes:
      - ./haproxy/2:/usr/local/etc/haproxy
    ports:
      - 8082:80
      - 8402:8404
    networks:
      - proxy-network

  ha-web3:
    image: haproxytech/haproxy-alpine:2.4
    restart: unless-stopped
    volumes:
      - ./haproxy/3:/usr/local/etc/haproxy
    ports:
      - 8083:80
      - 8403:8404
    networks:
      - proxy-network
networks:
  proxy-network:
